#!/usr/bin/env python
# encoding: utf-8
#Author - Jiarui Jin

import tweepy
from tweepy import OAuthHandler
import json
import wget

consumer_key = "olzksrVk97qC5pCYJFB0lTZva"
consumer_secret = "5Kg5hQlx0PumRCygVrTxxb6lHO9C7OHgOphGCeZrZ2cQ1uwL1F"
access_key = "1040408442765225991-YTfbydqnrVpx0W825HFi6aBjqaVcub"
access_secret = "imxWQsgNdcSbBU6mYxmfeyUYLmpCyhorxYQfslyvpqacT"


def get_all_tweets(screen_name):
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth)
        
    alltweets = []    
    
    #make initial request for most recent tweets (200 is the maximum allowed count)
    new_tweets = api.user_timeline(screen_name = screen_name,count=10)
    
    #save most recent tweets
    #.append different?
    alltweets.extend(new_tweets)
    
    #save the id of the oldest tweet less one
    oldest = alltweets[-1].id - 1
    
    #keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets) > 0:
        
        #all subsiquent requests use the max_id param to prevent duplicates
        new_tweets = api.user_timeline(screen_name = screen_name,count=10,max_id=oldest)
        
        #save most recent tweets
        alltweets.extend(new_tweets)
        
        #update the id of the oldest tweet less one
        oldest = alltweets[-1].id - 1
        if(len(alltweets) > 15):
            break
        print( "...%s tweets downloaded so far" % (len(alltweets)))

    #ger all media_url
    media_files = set()
    for status in alltweets:
        media = status.entities.get('media', [])
        if(len(media) > 0):
          media_files.add(media[0]['media_url'])
    
    #download the pictures from media_url
    for media_file in media_files:
      wget.download(media_file)
       
    #write tweet objects to JSON
    #file = open('tweet.json', 'w') 
    #print("Writing tweet objects to JSON please wait...")
    #for status in alltweets:
    #    json.dump(status._json,file,sort_keys = True,indent = 4)
    
    #close the file
    #print("Done")
    #file.close()

if __name__ == '__main__':
    #pass in the username of the account you want to download
    get_all_tweets("@Ibra_official")
